-- Enable UUID extension if not already enabled
create extension if not exists "uuid-ossp";

-- 1. Sessions Table (Meeting History)
create table if not exists sessions (
  id uuid default uuid_generate_v4() primary key,
  user_id uuid references auth.users not null,
  title text default 'Untitled Session',
  started_at timestamp with time zone default now(),
  ended_at timestamp with time zone,
  ai_summary text, -- Optional: Generated by LLM later
  action_items jsonb, -- Optional: List of tasks
  status text default 'live' -- 'live', 'completed', 'processing'
);

-- 2. Session Transcripts Table (Detailed Diarization)
create table if not exists session_transcripts (
  id uuid default uuid_generate_v4() primary key,
  session_id uuid references sessions(id) on delete cascade not null,
  speaker text default 'Speaker 0',
  text text not null,
  timestamp float not null, -- Seconds from start
  created_at timestamp with time zone default now()
);

-- 3. Row Level Security (RLS)
alter table sessions enable row level security;
alter table session_transcripts enable row level security;

-- Policies for Sessions
drop policy if exists "Users can view their own sessions" on sessions;
create policy "Users can view their own sessions"
  on sessions for select
  using (auth.uid() = user_id);

drop policy if exists "Users can insert their own sessions" on sessions;
create policy "Users can insert their own sessions"
  on sessions for insert
  with check (auth.uid() = user_id);

drop policy if exists "Users can update their own sessions" on sessions;
create policy "Users can update their own sessions"
  on sessions for update
  using (auth.uid() = user_id);

-- Policies for Transcripts
drop policy if exists "Users can view transcripts of their sessions" on session_transcripts;
create policy "Users can view transcripts of their sessions"
  on session_transcripts for select
  using (
    exists (
      select 1 from sessions
      where sessions.id = session_transcripts.session_id
      and sessions.user_id = auth.uid()
    )
  );

drop policy if exists "Users can insert transcripts into their sessions" on session_transcripts;
create policy "Users can insert transcripts into their sessions"
  on session_transcripts for insert
  with check (
    exists (
      select 1 from sessions
      where sessions.id = session_transcripts.session_id
      and sessions.user_id = auth.uid()
    )
  );
